### ISSUE TITLE
Timeout for welcomepage

### ISSUE THREAD

**Issue by m-kuhn** [rabits/dockerfiles#2]
Just as a reminder.
After a recent update to Qt 5.9.4 it was hanging at the welcome page and it took me quite some time to figure out this:

https://stackoverflow.com/a/47820171/2319028
https://github.com/opengisch/docker-qt-crystax/commit/13d3eab8d3178a66832e7422ac7e4efa4c2541eb

**Comment by rabits** [comment]
Oh my... Ok, will fix it - thank you)

**Comment by rabits** [comment]
Fixed here: 47f3717, dockerhub images was updated.
