### ISSUE TITLE
How to build 5.15-desktop locally?

### ISSUE THREAD

**Issue by LinqLover** [rabits/dockerfiles#6]
Cloned your repository, `cd`'ed into `5.15-desktop`, and ran `docker build .`:

```
Step 12/16 : RUN echo "${QT_INSTALLER_SHA256} -" > sum.txt && curl -fLs "${QT_INSTALLER_URL}" | tee /tmp/qt/installer.run | sha256sum -c sum.txt     && [ -z "${QT_CI_ENV_URL}" ] && echo "" > /tmp/qt/secrets.env || curl "${QT_CI_ENV_URL}" > /tmp/qt/secrets.env && . /tmp/qt/secrets.env     && QT_CI_PACKAGES=qt.qt5.$(echo "${QT_VERSION}" | tr -d .).${QT_BIN_PACKAGE},qt.tools.cmake,qt.tools.ninja /tmp/qt/extract-qt-installer.sh /tmp/qt/installer.run "${QT_PATH}"     && find "${QT_PATH}" -mindepth 1 -maxdepth 1 ! -name "${QT_VERSION}" ! -name "Tools" -exec echo 'Cleaning Qt SDK: {}' \; -exec rm -r '{}' \;     && rm -rf "${QT_PATH}/Tools/QtCreator" /tmp/qt /root/.local/share/Qt /root/.config/Qt
 ---> Running in d1c661af63b9
-: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
curl: (3) <url> malformed
The command '/bin/sh -c echo "${QT_INSTALLER_SHA256} -" > sum.txt && curl -fLs "${QT_INSTALLER_URL}" | tee /tmp/qt/installer.run | sha256sum -c sum.txt     && [ -z "${QT_CI_ENV_URL}" ] && echo "" > /tmp/qt/secrets.env || curl "${QT_CI_ENV_URL}" > /tmp/qt/secrets.env && . /tmp/qt/secrets.env     && QT_CI_PACKAGES=qt.qt5.$(echo "${QT_VERSION}" | tr -d .).${QT_BIN_PACKAGE},qt.tools.cmake,qt.tools.ninja /tmp/qt/extract-qt-installer.sh /tmp/qt/installer.run "${QT_PATH}"     && find "${QT_PATH}" -mindepth 1 -maxdepth 1 ! -name "${QT_VERSION}" ! -name "Tools" -exec echo 'Cleaning Qt SDK: {}' \; -exec rm -r '{}' \;     && rm -rf "${QT_PATH}/Tools/QtCreator" /tmp/qt /root/.local/share/Qt /root/.config/Qt' returned a non-zero code: 3
```

What am I doing wrong? How can I build this dockerfile locally on my end? My ultimate goal is to modify this dockerfile (I need to log into the container as user `root` (without specifying extra build args, [which is not supported by GitLab CI](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2750)) and to push it to a fork on hub.docker.com, but to do apparently I need to build it locally first ...

**Comment by rabits** [comment]
Hi @LinqLover , did you had a chance to read the readme file? https://github.com/rabits/dockerfiles#build-the-container-image-514-and-further-ones - I think it should solve all of it.

**Comment by LinqLover** [comment]
Thanks for the pointer. I actually have missed this section of the readme ...

So but how did you build the images available on Docker Hub? Does it matter in any way which credentials are used for installation? Are there some publicly available credentials so that I do not need to expose my personal credentials to the world? :-)

**Comment by rabits** [comment]
Actually manually, I found no good way of not putting the creds into the image and use them on dockerhub. So I built them locally and pushed to the hub.

So the way I used for manual build is not storing the creds on the docker image and cleans any configs on the image before bake. If you will use your creds and follow the procedure - they should not be exposed (but better to check twice).

**Comment by LinqLover** [comment]
Thank you, I will try that. Btw, did you try out the following? https://superuser.com/a/1524857

**Comment by rabits** [comment]
So actually I introduced the same (proxy fix) for 5.9 & 5.12 standalone installers in https://github.com/rabits/dockerfiles/commit/e5df46f094619d609772d4dea87c154ece4f8411 , but for 5.14 & 5.15 Dockerfiles uses online installer (Qt stopped to provide complete installers). I think there should be a way to disable internet for the "auth" phase of installer, but need to check how it will work.

**Comment by LinqLover** [comment]
One follow up question to the steps in the readme - is it important what to enter for the `YOUR_LOGIN` placeholder (I don't know what it does)? And how to determine the correct host IP address?

I tried both from below
```
docker build --pull --build-arg 'QT_CI_ENV_URL=http://172.17.0.1:8765/secrets.env' -t myqt .
docker build --pull --build-arg 'QT_CI_ENV_URL=http://172.20.11.1:8765/secrets.env' -t myqt .
```
but in either case, got a timeout in the same step 12/16 as above from the IP address. But the `curl` test is successful.
Do you have any idea what I could be doing wrong? :-)

**Comment by rabits** [comment]
No worries about YOUR_LOGIN - it's just a tag addition if you want to push the image somewhere - check `docker --help` to find out what the `-t` option is doing.

So to properly set the IP address of the host machine - you need to run curl command from the docker container (like from simple ubuntu or whatever you prefer). Also you can check the docker settings and figure out what the network it uses like:
```
host$ ip a
...
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:84:9a:7d:57 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:84ff:fe9a:7d57/64 scope link
       valid_lft forever preferred_lft forever
```
In your case it could use different interface, so it's necessary to check.

**Comment by rabits** [comment]
Ok, just tried to rebuild the image 5.15 myself - and seems the Qt guys are disabled the download.qt.io and master.qt.io ... Nice, will switch to the mirrors

**Comment by rabits** [comment]
Switched to berkeley mirror - it should work anyway. Also tested Qt online installed (3 & 4) without internet - nope, not working at all...
I think they will force me to switch to use the build process after all... But since 6th version is useless still - we have some time.

**Comment by LinqLover** [comment]
Thanks for the help. So now I have pulled your updates and fixed the credentials access (i.e. the python server reports a successful request of the secrets file), but I always get stuck during a later download stage:

```
[0] Language: C
[0] Arguments: /tmp/qt/installer.run, -v, --script, /tmp/tmp.Gbm3vjb4M
[0] Operations sanity check succeeded.
[1] Reading Qt Account settings from disk: "/root/.local/share/Qt/qtaccount.ini"
[1] Warning: Qt Account settings file [/root/.local/share/Qt/qtaccount.ini] does not exist.
[1] QtAccount information:
[1] Login completed: false
[2] Email: ""
[2] Total number of licenses: 0
[2] Account type: 3
...
[144] Loaded control script "/tmp/tmp.Gbm3vjb4M"
[144] Using control script: "/tmp/tmp.Gbm3vjb4M"
[152] Welcome Page
[159] Warning: Network error: [ QNetworkReply::UnknownNetworkError ] "Failed to connect to server. Check your network connection and try again."
[3308] Warning: Network error: [ QNetworkReply::UnknownNetworkError ] "Failed to connect to server. Check your network connection and try again."
```

Why is the account information empty after the secrets file could be loaded?

**Comment by LinqLover** [comment]
In general, it would be great if you could give the default docker user sudo rights. AFAIK in most of all cases, the docker images in your repository will be used in a CI where it's a very usual thing to install some other dependency - which is not possible without sudo rights. And not all CI services provide an easy way to log into the docker image with a custom user. :-)

**Comment by rabits** [comment]
Hi @LinqLover ,

As you see logs saying that:
```
[1] Login completed: false
[2] Email: ""
```
Means something wrong with your secret.env file. Please make sure you using the proper format, like that:
```
export QT_CI_LOGIN='your login'
export QT_CI_PASSWORD='your pass'
```

And regarding CI: sudo is bad, CI env should be untouched by the executor. So no sudo by default and I recommend to prepare a custom image with required components, add sudo into or run image as root.

**Comment by LinqLover** [comment]
> Please make sure you using the proper format, like that:
> 
> ```
> export QT_CI_LOGIN='your login'
> export QT_CI_PASSWORD='your pass'
> ```

I swear that my `secrets.env` as returned by the `curl` test looks exactly like yours (just with a real email address and password, of course). Hm ...

> And regarding CI: sudo is bad, CI env should be untouched by the executor. So no sudo by default and I recommend to prepare a custom image with required components, add sudo into or run image as root.

I see your point, but this is much less flexible and easy than simply writing your installation statements into a CI file, especially when you need to do CI debugging ... 🤔

**Comment by rabits** [comment]
> I swear that my secrets.env as returned by the curl test looks exactly like yours (just with a real email address and password, of course). Hm ...

Yep, I understand, but it's the only thing that could be missed. You can debug on your local in:
* https://github.com/rabits/dockerfiles/blob/master/5.15-desktop/Dockerfile#L49 - where it downloads the file and set the env vars
* https://github.com/rabits/dockerfiles/blob/master/5.15-desktop/extract-qt-installer.sh#L35 - where it uses env vars in the script

to find why the env var is not used properly.

So if we're talking about CI with docker - docker container is an environment. The environment should not be flexible. Otherwise you will quickly find yourself in a situation when developers tells you what kind of tools and what kind of security issues they want to introduce into the product. But as far as you have different Qt5.15 & Qt5.14 images - the same way I usually put tools into the environment (or combine containers via kubernetes pods to switch the tools).

As I said, I see 3 ways:
* Prepare you custom image and reuse it to save time on dynamic installation during CI run
* Prepare you custom image and put sudo there to have a way to install apps
* Run the existing image as root user (you can specify which user you want `docker run --user '0:0' ...`)

I definitely will not put sudo there, especially for debugging purposes :)

**Comment by LinqLover** [comment]
Hm ... looks as if the `CredentialsPageCallback` function is not reached at all (otherwise [my `docker build` output](https://github.com/rabits/dockerfiles/issues/6#issuecomment-764595456) would contain the string `Credentials Page` somewhere, wouldn't it?). Apparently `installer.run` does not call this function, but I cannot find its implementation (and probably it will be non-trivial to debug this, right?) 🤔

**Comment by rabits** [comment]
So unfortunately you can't use this output as a reference, because it was captured when it can't connect to network. Online installer requires internet connection on the welcome page.

**Comment by LinqLover** [comment]
And how can it be that my docker has no access to the internet when using the build steps from the readme?

**Comment by rabits** [comment]
Sorry, no idea - but what I see is:
```
[159] Warning: Network error: [ QNetworkReply::UnknownNetworkError ] "Failed to connect to server. Check your network connection and try again."
[3308] Warning: Network error: [ QNetworkReply::UnknownNetworkError ] "Failed to connect to server. Check your network connection and try again."
```
So something is wrong - and I suppose it's still not solved issue with connecting to the secrets as I described here: https://github.com/rabits/dockerfiles/issues/6#issuecomment-763242355

**Comment by rabits** [comment]
So I hope you sorted out the issue, if not - please reopen the ticket.
