### ISSUE TITLE
How to install MQTT in 5.15-desktop

### ISSUE THREAD

**Issue by filipesaraiva** [rabits/dockerfiles#7]
Hello, is it possible to install MQTT in 5.15-desktop? If yes, how can I do it? Directly by `apt`or do I need use some packages provided by QTC itelf?

All the best and thank you for this project!

**Comment by filipesaraiva** [comment]
Well, I managed to build that directly downloading [QtMQTT](git://code.qt.io/qt/qtmqtt.git), checking out the 5.15 tag, and running `qmake`, `make`, `make install`. That worked as expected.

The code is available as [Gitlab CI script](https://gitlab.com/ccsl-ufpa/ufpa-digital/-/blob/master/.gitlab-ci.yml), if anyone is interesting.

**Comment by rabits** [comment]
Thank you @filipesaraiva
